language: node_js
node_js:
  - "18.15.0"

before_install:
  - sudo apk update
  - apk --no-cache add zip
  - zip -h
  - unzip -h
  - sudo --no-cache add curl
  - curl -fsSL curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - aws -v

deploy:
  - provider: script
    script:
      - docker build -t kassimbabatunde/react-demo
      - docker start -p 8080:3000 kassimbabatunde/react-demo .
    on:
      branch: dev