sudo: require
services:
  - docker

before_install:
  - docker build -t kassimbabatunde/react-demo -f Dockerfile .

script:
  - docker run -e CI=true -p 8080:3000 kassimbabatunde/react-demo npm run test 